baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Laura Arevalo | Data Manager'
theme = 'introduction'

[params]
    showMenu = false
    themeStyle = "auto"
    customCSS = ["customCSS.css"]