baseURL = '/'
languageCode = 'es-ES'
title = 'Laura Arevalo | Data Engineer'
theme = ''

[params]
    showMenu = true
    themeStyle = "auto"

[security]
  [security.funcs]
    getenv = ['^HUGO_', '^CI$', 'WC_POST_CSS']

[build]
  noJSConfigInAssets = false
  useResourceCacheWhen = 'fallback'
  [build.buildStats]
    disableClasses = false
    disableIDs = false
    disableTags = false
    enable = false
  [[build.cacheBusters]]
    source = '(postcss|tailwind)\.config\.js'
    target = '(css|styles|scss|sass)'