[build]
  publish = "public"
  command = "hugo --gc --minify"
  commandOrigin: "config"

[build.environment]
  HUGO_VERSION = "0.139.4"  

[context.production.environment]
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"

[context.branch-deploy]
  command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"

[context.deploy-preview]
  command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"